"""add_metric_to_tasks

Revision ID: 0452c8f52933
Revises: 640f4b99245d
Create Date: 2025-02-25 17:14:28.514246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0452c8f52933'
down_revision: Union[str, None] = '640f4b99245d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_title'), 'goals', ['title'], unique=False)
    op.drop_index('ix_metrics_new_id', table_name='metrics')
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.add_column('tasks', sa.Column('metric_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('contribution_value', sa.Float(), nullable=True))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'tasks', 'metrics', ['metric_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('tasks', 'contribution_value')
    op.drop_column('tasks', 'metric_id')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.create_index('ix_metrics_new_id', 'metrics', ['id'], unique=False)
    op.drop_index(op.f('ix_goals_title'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    # ### end Alembic commands ###
