"""add_completion_order_to_tasks

Revision ID: 0d7e07324acd
Revises: 0452c8f52933
Create Date: 2025-02-25 17:18:23.796835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7e07324acd'
down_revision: Union[str, None] = '0452c8f52933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_new_id', table_name='metrics')
    op.add_column('tasks', sa.Column('completion_order', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tasks', 'completion_order')
    op.create_index('ix_metrics_new_id', 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###
