"""update_metric_type_enum

Revision ID: 2033a0c3d415
Revises: d63a9bd864c0
Create Date: 2025-02-25 17:03:07.380221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2033a0c3d415'
down_revision: Union[str, None] = 'd63a9bd864c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
