"""Add contributions_list to metrics

Revision ID: 61403562c419
Revises: 4ed615712cb1
Create Date: 2025-02-25 18:22:20.658712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '61403562c419'
down_revision: Union[str, None] = '4ed615712cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_contributions_id', table_name='metric_contributions')
    op.drop_table('metric_contributions')
    op.add_column('metrics', sa.Column('contributions_list', sqlite.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'contributions_list')
    op.create_table('metric_contributions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metric_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_contributions_id', 'metric_contributions', ['id'], unique=False)
    # ### end Alembic commands ###
