"""Add parent_id to goals

Revision ID: 7cb2abc39ec7
Revises: 33bf420ef2d1
Create Date: 2025-02-24 23:15:04.335377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb2abc39ec7'
down_revision: Union[str, None] = '33bf420ef2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals') as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('title', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True, existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True, existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("'1'"))
        batch_op.create_foreign_key('fk_goals_parent', 'goals', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(op.f('ix_goals_id'), ['id'], unique=False)

    with op.batch_alter_table('tasks') as batch_op:
        batch_op.create_foreign_key('fk_tasks_goals', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.drop_constraint('fk_tasks_goals', type_='foreignkey')

    with op.batch_alter_table('goals') as batch_op:
        batch_op.drop_constraint('fk_goals_parent', type_='foreignkey')
        batch_op.drop_index(op.f('ix_goals_id'))
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("'1'"))
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False, existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False, existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('title', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column('parent_id')
