"""Add is_starred and scheduled_time to tasks

Revision ID: cc50b7c5a3ee
Revises: 7be89b580fae
Create Date: 2025-03-06 10:25:10.012471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cc50b7c5a3ee'
down_revision: Union[str, None] = '7be89b580fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategies_id', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_experiences_id', table_name='experiences')
    op.drop_table('experiences')
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.add_column('tasks', sa.Column('is_starred', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scheduled_time')
    op.drop_column('tasks', 'is_starred')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.create_table('experiences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('goal_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiences_id', 'experiences', ['id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('steps', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('goal_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategies_id', 'strategies', ['id'], unique=False)
    # ### end Alembic commands ###
