"""Add parent-child relationships to goal targets

Revision ID: fca467978fe0
Revises: 366719bb6f20
Create Date: 2025-03-13 11:40:22.099928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fca467978fe0'
down_revision: Union[str, None] = '366719bb6f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_experiences_id', table_name='experiences')
    op.drop_table('experiences')
    op.drop_index('ix_strategies_id', table_name='strategies')
    op.drop_table('strategies')
    
    # Add the foreign key constraint for the existing goaltarget_parent_id column
    with op.batch_alter_table('goal_targets') as batch_op:
        batch_op.create_foreign_key(
            'fk_goaltarget_parent', 
            'goal_targets', 
            ['goaltarget_parent_id'], 
            ['id'], 
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the foreign key constraint
    with op.batch_alter_table('goal_targets') as batch_op:
        batch_op.drop_constraint('fk_goaltarget_parent', type_='foreignkey')
    
    # Recreate the dropped tables
    op.create_table('strategies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('steps', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('goal_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategies_id', 'strategies', ['id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('goal_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiences_id', 'experiences', ['id'], unique=False)
    # ### end Alembic commands ###
